version: 2.1

jobs:
  run-test:
    docker:
      - image: cimg/node:21.0.0
    steps:
      - checkout
      - run: npm i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run test
          command: PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test --reporter=junit --project=chromium
      - store_test_results:
          path: results.xml

workflows:
  run-test-workflow:
    jobs:
      - run-test